### ISSUE TITLE
Choose compiler

### ISSUE THREAD

**Issue by Sync-07** [Jaseunda/scode-studio#1]
![Screenshot_2021-11-07-01-34-44-83](https://user-images.githubusercontent.com/87580874/140618692-14b74b92-d728-491c-8768-7e7ac62ca03e.jpg)
I selected the 'Choose Compiler' choice, then what am I supposed to do next?

What I'm thinking to do is to select the directory of my compiler and I thought it will redirect to the file manager to let me choose the directory once I tapped on the 'Choose Compiler' choice. Am I doing things wrong?

**Comment by Jaseunda** [comment]
Clicking the **choose compiler** wont open the directory. If you want to run your code u should.

Click built-in and click the run button.
